### ISSUE TITLE
更改frame中type bits的存储方式

### ISSUE THREAD

**Issue by RobertIndie** [RobertIndie/moss#32]
之前的逻辑是将bits放进GenericFrameLayout.data的前部，现在则是改为把bits放到GenericFrameLayout.frame_type中，并更改相应的转换逻辑和相关的单元测试代码。

除此之外，还需将GenericFrameLayout的frame_type这个变量名改为frame_type_bits。

**Comment by YHTB** [comment]
完成

**Comment by RobertIndie** [comment]
还有一些问题：
frame_type_bits是和注释中的type进行挂钩的，现在的代码只是单纯处理了StreamFrame 的bits。
STREAM帧导出的GFL的frame_type_bits应该介于0x08和0x0f。目前的单元测试用例代码中是直接把bits赋值给frame_type_bits，这样是不正确的。
而其他帧的frame_type_bits则直接使用注释中的type即可

**Comment by RobertIndie** [comment]
Fixed in #35 .
